Give dimensions unique names.
Before this change assembling the DataArrays into one Dataset
raised an error because multiple DataArrays used the same dimension name
(such as ``dim_0``) to mean different things. Xarray detected that
one DataArrays's ``dim_0`` had a different shape than another
DataArray's ``dim_0`` and thus (correctly!) refused to combine them into
one Dataset, raising an error like:

```
ValueError: arguments without labels along dimension 'dim_0' cannot be aligned because they have different dimension sizes: {1, 2, 3, 4, 5, 38, 7, 14, 18}
```

This PR ensures unique dimension names across the whole Dataset. This
fallback will become less important once we start providing names for
the dimensions through ``device.describe()``, making use of the 'dims'
key that was added to the event model.